# Lab04- Multi-variable Linear Regression

In [4]:
import tensorflow as tf
import numpy as np

In [5]:
tf.random.set_seed(0) 

In [7]:
x1_data = [1, 0, 3, 0, 5]
x2_data = [0, 2, 0, 4, 0]
y_data = [1, 2, 3, 4, 5]

W1 = tf.Variable(tf.random.uniform((1,),-10.0,10.0))
W2 = tf.Variable(tf.random.uniform((1,),-10.0,10.0))
b = tf.Variable(tf.random.uniform((1,),-10.0,10.0))

learning_rate = tf.Variable(0.001)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = W1 * x1_data + W2 * x2_data + b
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))
    W1_grad, W2_grad, b_grad = tape.gradient(cost, [W1, W2, b])
    W1.assign_sub(learning_rate * W1_grad)
    W2.assign_sub(learning_rate * W2_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
          i, cost.numpy(), W1.numpy()[0], W2.numpy()[0], b.numpy()[0]))

    0 | 335.280823 |    -4.0663 |     1.1220 |  -6.065215
   50 |  76.037262 |    -0.8001 |     1.6209 |  -4.978779
  100 |  18.959265 |     0.7151 |     1.8781 |  -4.429109
  150 |   6.310240 |     1.4125 |     2.0104 |  -4.134423
  200 |   3.445082 |     1.7284 |     2.0768 |  -3.961648
  250 |   2.743659 |     1.8667 |     2.1075 |  -3.847750
  300 |   2.525401 |     1.9225 |     2.1184 |  -3.762738
  350 |   2.417754 |     1.9402 |     2.1181 |  -3.692262
  400 |   2.337300 |     1.9403 |     2.1114 |  -3.629400
  450 |   2.264998 |     1.9325 |     2.1008 |  -3.570778
  500 |   2.196329 |     1.9213 |     2.0881 |  -3.514729
  550 |   2.130126 |     1.9085 |     2.0741 |  -3.460409
  600 |   2.066037 |     1.8953 |     2.0595 |  -3.407385
  650 |   2.003917 |     1.8819 |     2.0444 |  -3.355424
  700 |   1.943679 |     1.8686 |     2.0293 |  -3.304398
  750 |   1.885258 |     1.8555 |     2.0141 |  -3.254230
  800 |   1.828595 |     1.8425 |     1.9990 |  -3.204873
  850 |   1.77

## Simple Example (2 variables with Matrix)

In [10]:
x_data = [[1., 0., 3., 0., 5.],[0., 2., 0., 4., 0.]]
y_data  = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random.uniform((1, 2), -1.0, 1.0))
b = tf.Variable(tf.random.uniform((1,), -1.0, 1.0))

learning_rate = tf.Variable(0.001)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(W, x_data) + b # (1, 2) * (2, 5) = (1, 5)
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))

        W_grad, b_grad = tape.gradient(cost, [W, b])
        W.assign_sub(learning_rate * W_grad)
        b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], b.numpy()[0]))

    0 |   1.618855 |     0.5593 |     0.7060 |   0.059437
   50 |   0.393978 |     0.7683 |     0.7928 |   0.137434
  100 |   0.106617 |     0.8647 |     0.8455 |   0.175210
  150 |   0.035609 |     0.9089 |     0.8782 |   0.193109
  200 |   0.016568 |     0.9292 |     0.8989 |   0.201033
  250 |   0.010827 |     0.9386 |     0.9122 |   0.203861
  300 |   0.008804 |     0.9431 |     0.9210 |   0.204037
  350 |   0.007938 |     0.9454 |     0.9269 |   0.202809
  400 |   0.007471 |     0.9468 |     0.9311 |   0.200825
  450 |   0.007155 |     0.9478 |     0.9341 |   0.198434
  500 |   0.006903 |     0.9486 |     0.9363 |   0.195824
  550 |   0.006681 |     0.9493 |     0.9381 |   0.193102
  600 |   0.006474 |     0.9500 |     0.9395 |   0.190330
  650 |   0.006276 |     0.9507 |     0.9408 |   0.187544
  700 |   0.006087 |     0.9515 |     0.9419 |   0.184765
  750 |   0.005903 |     0.9522 |     0.9429 |   0.182006
  800 |   0.005726 |     0.9529 |     0.9439 |   0.179275
  850 |   0.00

## Hypothesis without b


#### bias(b) 추가

In [11]:
x_data = [[1., 1., 1., 1., 1.],[1., 0., 3., 0., 5.], [0., 2., 0., 4., 0.]]
y_data  = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random.uniform((1, 3), -1.0, 1.0))

learning_rate = 0.001
optimizer = tf.keras.optimizers.SGD(learning_rate)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(W, x_data) # b가 없다
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))

    grads = tape.gradient(cost, [W])
    optimizer.apply_gradients(grads_and_vars=zip(grads,[W]))
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.4f}".format(i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], W.numpy()[0][2]))

    0 |  36.285358 |    -0.2704 |    -0.5845 |    -0.9307
   50 |  10.381646 |     0.1304 |     0.2208 |    -0.2883
  100 |   3.325259 |     0.3392 |     0.5817 |     0.1130
  150 |   1.199020 |     0.4490 |     0.7406 |     0.3664
  200 |   0.488739 |     0.5066 |     0.8089 |     0.5281
  250 |   0.229629 |     0.5359 |     0.8374 |     0.6322
  300 |   0.128566 |     0.5495 |     0.8488 |     0.6999
  350 |   0.087015 |     0.5542 |     0.8534 |     0.7443
  400 |   0.068979 |     0.5538 |     0.8555 |     0.7739
  450 |   0.060518 |     0.5503 |     0.8568 |     0.7939
  500 |   0.056035 |     0.5451 |     0.8580 |     0.8077
  550 |   0.053237 |     0.5388 |     0.8594 |     0.8175
  600 |   0.051169 |     0.5319 |     0.8609 |     0.8248
  650 |   0.049435 |     0.5246 |     0.8626 |     0.8303
  700 |   0.047867 |     0.5172 |     0.8644 |     0.8348
  750 |   0.046394 |     0.5097 |     0.8662 |     0.8385
  800 |   0.044985 |     0.5022 |     0.8681 |     0.8417
  850 |   0.04

## Custom Gradient


##### tf.train.GradientDescentOptimizer(): optimizer
##### optimizer.apply_gradients(): update

In [12]:
X = tf.constant([[1., 2.], [3., 4.]])
y = tf.constant([[1.5], [3.5]])

W = tf.Variable(tf.random.normal((2, 1)))
b = tf.Variable(tf.random.normal((1,)))

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

n_epoch = 1000+1
print("epoch | cost")
for i in range(n_epoch):
    #Use tf.GradientTape to record the gradient of the cost function
    with tf.GradientTape() as tape:
        y_pred = tf.matmul(X, W) + b
        cost = tf.reduce_mean(tf.square(y_pred - y))

    #calculates the gradients of the loss
    grads = tape.gradient(cost, [W, b])
    
    #updates parameters (W and b)
    optimizer.apply_gradients(grads_and_vars=zip(grads, [W, b]))
    if i % 50 == 0:
        print("{:5} | {:10.6f}".format(i, cost.numpy()))

epoch | cost
    0 |  55.870758
   50 |   0.019156
  100 |   0.013097
  150 |   0.008954
  200 |   0.006122
  250 |   0.004186
  300 |   0.002862
  350 |   0.001957
  400 |   0.001338
  450 |   0.000915
  500 |   0.000625
  550 |   0.000428
  600 |   0.000292
  650 |   0.000200
  700 |   0.000137
  750 |   0.000093
  800 |   0.000064
  850 |   0.000044
  900 |   0.000030
  950 |   0.000020
 1000 |   0.000014


## Predicting exam score

In [13]:
tf.random.set_seed(0)

In [15]:
# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# weights
w1 = tf.Variable(10.)
w2 = tf.Variable(10.)
w3 = tf.Variable(10.)
b  = tf.Variable(10.)

learning_rate = 0.000001

for i in range(1000+1):
    # tf.GradientTape() to record the graient of the cost function
    with tf.GradientTape() as tape:
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1,w2,w3,b])
    #update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
        print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 | 5793889.5000
   50 |   64291.1484
  100 |     715.2902
  150 |       9.8462
  200 |       2.0152
  250 |       1.9252
  300 |       1.9210
  350 |       1.9177
  400 |       1.9145
  450 |       1.9114
  500 |       1.9081
  550 |       1.9050
  600 |       1.9018
  650 |       1.8986
  700 |       1.8955
  750 |       1.8923
  800 |       1.8892
  850 |       1.8861
  900 |       1.8829
  950 |       1.8798
 1000 |       1.8767


## Multi-variable Linear Regression(1)

In [17]:
# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# random weights
w1 = tf.Variable(tf.random.normal((1,)))
w2 = tf.Variable(tf.random.normal((1,)))
w3 = tf.Variable(tf.random.normal((1,)))
b  = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

for i in range(1000+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
    
    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
      print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 |    3528.1030
   50 |      92.7332
  100 |      54.4777
  150 |      53.9173
  200 |      53.7753
  250 |      53.6384
  300 |      53.5022
  350 |      53.3662
  400 |      53.2305
  450 |      53.0953
  500 |      52.9603
  550 |      52.8258
  600 |      52.6917
  650 |      52.5578
  700 |      52.4243
  750 |      52.2911
  800 |      52.1583
  850 |      52.0259
  900 |      51.8939
  950 |      51.7621
 1000 |      51.6306


## Multi-variable Linear Regression(2)

##### Matrix 사용

In [18]:
# x1, x2, x3, y
data = np.array([[ 73.,  80.,  75., 152. ],[ 93.,  88.,  93., 185. ],[ 89.,  91.,  90., 180. ],[ 96.,  98., 100., 196. ],[ 73.,  66.,  70., 142. ]], dtype=np.float32)

# slice data
X = data[:, :-1]
y = data[:, [-1]]

W = tf.Variable(tf.random.normal((3, 1)))
b = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

# hypothesis, prediction function
def predict(X):
    return tf.matmul(X, W) + b

print("epoch | cost")

n_epochs = 2000
for i in range(n_epochs+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean((tf.square(predict(X) - y)))

    # calculates the gradients of the loss
    W_grad, b_grad = tape.gradient(cost, [W, b])

    # updates parameters (W and b)
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 100 == 0:
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

epoch | cost
    0 |  3743.1343
  100 |     3.6005
  200 |     3.1265
  300 |     3.1128
  400 |     3.0994
  500 |     3.0860
  600 |     3.0726
  700 |     3.0593
  800 |     3.0460
  900 |     3.0329
 1000 |     3.0199
 1100 |     3.0069
 1200 |     2.9939
 1300 |     2.9811
 1400 |     2.9682
 1500 |     2.9555
 1600 |     2.9429
 1700 |     2.9303
 1800 |     2.9177
 1900 |     2.9053
 2000 |     2.8929


In [19]:
W.numpy()

array([[ 1.0821941 ],
       [ 0.9810675 ],
       [-0.05930979]], dtype=float32)

In [20]:
b.numpy()

array([1.3517823], dtype=float32)

In [21]:
tf.matmul(X,W) +b

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[154.3891 ],
       [182.81396],
       [181.60631],
       [195.45604],
       [140.9507 ]], dtype=float32)>

## predict

In [22]:
Y # 실제값

[152.0, 185.0, 180.0, 196.0, 142.0]

In [23]:
predict(X).numpy() # 예측값

array([[154.3891 ],
       [182.81396],
       [181.60631],
       [195.45604],
       [140.9507 ]], dtype=float32)

In [25]:
# 새로운 데이터에 대한 예측

predict([[ 89.,  95.,  92.],[ 84.,  92.,  85.]]).numpy()

array([[185.41197],
       [177.47295]], dtype=float32)