# lab-12-0-rnn-basics-keras-eager

In [2]:
# setup
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential, Model

print(tf.__version__)

2.5.0


## Preparing dataset

In [3]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

## One cell: 4 (input_dim) in 2 (hidden_size)

In [4]:
# One cell RNN input_dim (4) -> output_dim (2)
x_data = np.array([[h]], dtype=np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size) # creating SimpleRNNCell
rnn = layers.RNN(cell, return_sequences=True, return_state=True) # analogous to tf.nn.dynamic_rnn
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.75035316 -0.75911593]]], shape: (1, 1, 2)
states: [[-0.75035316 -0.75911593]], shape: (1, 2)


In [5]:
# equivalent to above case
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True,
                       return_state=True) # layers.SimpleRNNCell + layers.RNN

outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.06409216  0.33891198]]], shape: (1, 1, 2)
states: [[-0.06409216  0.33891198]], shape: (1, 2)


## Unfolding to n sequences

In [6]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4) 

outputs: [[[ 0.36450136  0.5311629 ]
  [-0.58015275  0.14804101]
  [-0.6679625  -0.57617736]
  [-0.6802451  -0.8822647 ]
  [-0.3548778  -0.9426156 ]]], shape: (1, 5, 2) 

states: [[-0.3548778 -0.9426156]], shape: (1, 2)


## Batching input

In [7]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[-0.25771114 -0.7358563 ]
  [-0.8264204  -0.5415024 ]
  [-0.481155    0.04128402]
  [ 0.1432467   0.1481679 ]
  [ 0.6602772   0.10124869]]

 [[-0.4190176  -0.3212638 ]
  [ 0.07257547  0.22877866]
  [ 0.56681335 -0.1547552 ]
  [ 0.5814704  -0.65340734]
  [ 0.2830945  -0.8046877 ]]

 [[ 0.397449   -0.24186242]
  [ 0.45368224 -0.6087327 ]
  [-0.5536164  -0.78995585]
  [-0.88701844 -0.39155006]
  [-0.42034143  0.18182525]]], shape: (3, 5, 2) 

states: [[ 0.6602772   0.10124869]
 [ 0.2830945  -0.8046877 ]
 [-0.42034143  0.18182525]], shape: (3, 2)
